name: Build and deploy .NET Core application to Web App SWP391-1817-NET-G2
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: SWP391-1817-NET-G2
  AZURE_WEBAPP_PACKAGE_PATH: .\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  SOLUTION_FILE_PATH: BE/SWP391_1817-NET_G2.sln
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}
      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet test ${{ env.SOLUTION_FILE_PATH }} --no-build
      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_FILE_PATH }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.SWP391_1817_NET_G2_D0DA }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
